"""Chinese presentation labels for financial report extraction output."""

FIELD_LABELS = {
    "document_type": "文档类型",
    "source_file": "来源文件",
    "customer_id": "客户编号",
    "company_info": "企业信息",
    "balance_sheet": "资产负债表",
    "income_statement": "利润表",
    "cash_flow_statement": "现金流量表",
    "equity_change_statement": "所有者权益变动表",
    "financial_ratios": "财务指标",
    "bank_credit_analysis": "银行授信分析",
    "evidence": "证据链",
    "validation_warnings": "数据校验提示",
    "trend_metrics": "趋势指标",
    "report_markdown": "报告内容",
    "raw_value": "原始值",
    "normalized_value": "标准化数值",
    "previous_raw_value": "对比列原始值",
    "previous_normalized_value": "对比列标准化数值",
    "current_value": "当前值",
    "compare_value": "对比值",
    "current_column_label": "当前列名称",
    "previous_column_label": "对比列名称",
    "source_page": "来源页码",
    "source_text": "来源文本",
    "confidence": "置信度",
    "field_path": "字段路径",
    "table_name": "表名",
    "row_label": "行项目",
    "column_label": "列项目",
    "raw_text": "原始文本",
    "period": "所属期间",
    "beginning_equity": "期初所有者权益",
    "owner_contributions": "所有者投入资本",
    "profit_distribution": "利润分配",
    "comprehensive_income": "综合收益",
    "ending_equity": "期末所有者权益",
}

COMPANY_INFO_LABELS = {
    "accounting_standard": "会计准则",
    "report_type": "报表类型",
    "report_period_start": "所属期开始日期",
    "report_period_end": "所属期结束日期",
    "company_name": "企业名称",
    "taxpayer_id": "纳税人识别号",
    "report_date": "报送日期",
    "currency": "币种",
    "unit": "金额单位",
}

BALANCE_SHEET_LABELS = {
    "cash_and_equivalents": "货币资金",
    "trading_financial_assets": "交易性金融资产",
    "notes_receivable": "应收票据",
    "accounts_receivable": "应收账款",
    "receivables_financing": "应收款项融资",
    "prepayments": "预付款项",
    "other_receivables": "其他应收款",
    "inventory": "存货",
    "current_assets_total": "流动资产合计",
    "long_term_equity_investment": "长期股权投资",
    "fixed_assets": "固定资产",
    "construction_in_progress": "在建工程",
    "intangible_assets": "无形资产",
    "long_term_prepaid_expenses": "长期待摊费用",
    "non_current_assets_total": "非流动资产合计",
    "total_assets": "资产总计",
    "short_term_loans": "短期借款",
    "notes_payable": "应付票据",
    "accounts_payable": "应付账款",
    "advance_receipts": "预收款项",
    "contract_liabilities": "合同负债",
    "employee_benefits_payable": "应付职工薪酬",
    "taxes_payable": "应交税费",
    "other_payables": "其他应付款",
    "current_liabilities_total": "流动负债合计",
    "non_current_liabilities_due_within_one_year": "一年内到期的非流动负债",
    "long_term_loans": "长期借款",
    "non_current_liabilities_total": "非流动负债合计",
    "total_liabilities": "负债合计",
    "paid_in_capital": "实收资本",
    "capital_reserve": "资本公积",
    "surplus_reserve": "盈余公积",
    "undistributed_profit": "未分配利润",
    "total_equity": "所有者权益合计",
    "total_liabilities_and_equity": "负债和所有者权益总计",
}

INCOME_STATEMENT_LABELS = {
    "revenue": "营业收入",
    "operating_cost": "营业成本",
    "taxes_and_surcharges": "税金及附加",
    "selling_expenses": "销售费用",
    "admin_expenses": "管理费用",
    "rd_expenses": "研发费用",
    "finance_expenses": "财务费用",
    "interest_expense": "利息费用",
    "interest_income": "利息收入",
    "other_income": "其他收益",
    "investment_income": "投资收益",
    "operating_profit": "营业利润",
    "non_operating_income": "营业外收入",
    "non_operating_expense": "营业外支出",
    "total_profit": "利润总额",
    "income_tax_expense": "所得税费用",
    "net_profit": "净利润",
    "comprehensive_income_total": "综合收益总额",
}

CASH_FLOW_LABELS = {
    "cash_received_from_sales": "销售商品、提供劳务收到的现金",
    "tax_refund_received": "收到的税费返还",
    "other_cash_received_related_to_operating": "收到其他与经营活动有关的现金",
    "operating_cash_inflow_total": "经营活动现金流入小计",
    "cash_paid_for_goods_services": "购买商品、接受劳务支付的现金",
    "cash_paid_to_employees": "支付给职工以及为职工支付的现金",
    "taxes_paid": "支付的各项税费",
    "other_cash_paid_related_to_operating": "支付其他与经营活动有关的现金",
    "operating_cash_outflow_total": "经营活动现金流出小计",
    "net_operating_cash_flow": "经营活动产生的现金流量净额",
    "cash_received_from_investment_recovery": "收回投资收到的现金",
    "investment_income_cash_received": "取得投资收益收到的现金",
    "cash_received_from_disposal_assets": "处置长期资产收回的现金净额",
    "investing_cash_inflow_total": "投资活动现金流入小计",
    "cash_paid_for_fixed_intangible_assets": "购建长期资产支付的现金",
    "cash_paid_for_investments": "投资支付的现金",
    "investing_cash_outflow_total": "投资活动现金流出小计",
    "net_investing_cash_flow": "投资活动产生的现金流量净额",
    "cash_received_from_investors": "吸收投资收到的现金",
    "cash_received_from_borrowings": "取得借款收到的现金",
    "financing_cash_inflow_total": "筹资活动现金流入小计",
    "cash_paid_for_debt_repayment": "偿还债务支付的现金",
    "cash_paid_for_dividends_profit_interest": "分配股利、利润或偿付利息支付的现金",
    "financing_cash_outflow_total": "筹资活动现金流出小计",
    "net_financing_cash_flow": "筹资活动产生的现金流量净额",
    "net_cash_increase": "现金及现金等价物净增加额",
    "beginning_cash_balance": "期初现金及现金等价物余额",
    "ending_cash_balance": "期末现金及现金等价物余额",
}

FINANCIAL_RATIO_LABELS = {
    "asset_liability_ratio": "资产负债率",
    "debt_to_equity_ratio": "负债权益比",
    "current_ratio": "流动比率",
    "quick_ratio": "速动比率",
    "cash_ratio": "现金比率",
    "interest_bearing_debt": "有息负债",
    "short_debt_cash_coverage": "短债现金覆盖率",
    "gross_profit": "毛利润",
    "gross_margin": "毛利率",
    "operating_margin": "营业利润率",
    "net_margin": "净利率",
    "expense_ratio": "期间费用率",
    "operating_cash_flow_to_revenue": "经营现金流收入比",
    "sales_cash_collection_ratio": "销售现金回笼率",
    "operating_cash_flow_to_short_term_debt": "经营现金流短债覆盖率",
    "financing_dependence": "筹资依赖度",
    "ar_turnover": "应收账款周转率",
    "inventory_turnover": "存货周转率",
    "total_asset_turnover": "总资产周转率",
}

BANK_CREDIT_ANALYSIS_LABELS = {
    "overall_risk_level": "综合风险等级",
    "credit_view": "授信观点",
    "positive_factors": "有利因素",
    "negative_factors": "不利因素",
    "key_bank_questions": "银行审核关注点",
    "missing_materials": "缺失材料",
    "suggested_credit_strategy": "建议授信策略",
    "risk_findings": "风险发现",
    "code": "风险代码",
    "risk_level": "风险等级",
    "title": "风险标题",
    "description": "风险说明",
    "suggestion": "核查建议",
    "material": "材料名称",
    "reason": "补充原因",
    "priority": "优先级",
}

EVIDENCE_FIELD_LABELS = {
    "field_path": "字段路径",
    "source_file": "来源文件",
    "source_page": "来源页码",
    "table_name": "表名",
    "row_label": "行项目",
    "column_label": "列项目",
    "raw_text": "原始文本",
    "confidence": "置信度",
}

VALUE_LABELS = {
    "financial_report": "财务报表",
    "financial_data": "财务报表",
    "annual": "年报",
    "quarterly": "季报",
    "monthly": "月报",
    "unknown": "-",
    "CNY": "人民币",
    "enterprise_accounting_standard": "企业会计准则一般企业",
    "small_enterprise_accounting_standard": "小企业会计准则",
    "small_business_accounting_standard": "小企业会计准则",
    "business_accounting_standard": "企业会计准则",
    "low": "低",
    "medium": "中",
    "medium_high": "中高",
    "high": "高",
    "continuous_negative_operating_cash_flow": "经营现金流连续为负",
    "profit_positive_cashflow_negative": "盈利与现金流背离",
    "low_cash": "货币资金过低",
    "high_short_term_loans": "短期借款过高",
    "high_other_receivables": "其他应收款占比过高",
    "high_prepayments": "预付款项占比过高",
    "high_asset_liability_ratio": "资产负债率过高",
    "weak_equity": "净资产基础较弱",
    "financing_covers_operating_gap": "筹资现金流补经营现金流缺口",
    "loan_with_zero_interest_expense": "存在借款但利息费用为零",
    "declining_revenue": "收入下滑",
    "declining_assets": "资产总额下降",
    "abnormal_accounts_receivable_growth": "应收账款异常增长",
    "abnormal_inventory_growth": "存货异常增长",
    "abnormal_gross_margin_change": "毛利率异常波动",
}
