bind 127.0.0.1
port 6379
daemonize no
supervised systemd
pidfile /run/redis/redis-server.pid
dir /var/lib/redis
loglevel notice
appendonly yes
appendfsync everysec
save 900 1
save 300 10
save 60 10000
protected-mode yes
