export const BRAND = {
  appName: '沪上银企业信息服务平台',
  shortName: '沪上银',
  subtitle: '企业信息与融资资料服务系统',
  loginTitle: '上海孜友信息科技有限公司',
  loginSubtitle: '企业信息服务平台',
  version: 'V1.6.13',
  workspaceTitle: '沪上银企业信息服务平台',
  workspaceDescription: '集中查看客户业务进展、系统动态和方案产品库状态，适合企业信息服务与融资辅助系统的日常处理与演示验收。',
  riskReportCenter: '沪上银风险评估中心',
  riskReportFooter: '沪上银企业信息服务平台',
  organizer: '上海孜友信息科技有限公司',
  icpRecord: '沪ICP备2026022223号',
  icpRecordUrl: 'https://beian.miit.gov.cn/',
} as const;
